table kbo_Query
	lineageTag: ac7a373e-4c94-487c-803d-f5509b60bd70

	measure CustomerType =
			
			VAR LastOrderDate = MAXX(SUMMARIZE(kbo_Query, kbo_Query[EXT_ENTITY_ID]), MAX(kbo_Query[order_dt]))
			VAR SetupDate = MAX(kbo_Query[CUSTOMER_SETUP_DT])
			VAR DaysBetween = DATEDIFF(LastOrderDate, SetupDate, DAY)
			RETURN
			    IF(DaysBetween <= 2, "New", "Existing")
		lineageTag: d86086b1-9f9c-4cc6-ba2f-b7ebc628f927

		changedProperty = IsHidden

	column ORDER_ID
		dataType: string
		lineageTag: 280743f4-d718-4fe4-8a3d-93e395ac7150
		summarizeBy: none
		sourceColumn: ORDER_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDER_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 95db26f9-9587-47c7-840b-e749411cd4bf
		summarizeBy: none
		sourceColumn: ORDER_DT

		variation Variation
			isDefault
			relationship: 455d9ea0-01be-4232-8702-2ddfa793fd99
			defaultHierarchy: LocalDateTable_cdfd0690-7d63-408c-b2ca-ee9d044dd66f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EXT_ENTITY_ID
		dataType: string
		lineageTag: e8f9a942-3706-46ca-bbc1-2c6eb1eb6c23
		summarizeBy: none
		sourceColumn: EXT_ENTITY_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LINE_ITEMS_TOTAL_AMT
		dataType: double
		lineageTag: 9da655dd-df42-401f-b0fb-1b3a18b81824
		summarizeBy: sum
		sourceColumn: LINE_ITEMS_TOTAL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REVENUE
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f6597999-a5d1-462c-a225-4a23db24ac2e
		summarizeBy: sum
		sourceColumn: REVENUE

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column QTY
		dataType: int64
		formatString: 0
		lineageTag: a2d4ae4a-68f1-4e2a-9009-b90733e939a7
		summarizeBy: sum
		sourceColumn: QTY

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column PRICE
		dataType: double
		lineageTag: 6339d72b-ea5a-48b3-81b8-8689b270ad62
		summarizeBy: sum
		sourceColumn: PRICE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SKU_ID
		dataType: string
		lineageTag: 78116774-4c3d-4c41-bc38-5728a9ec29e1
		summarizeBy: none
		sourceColumn: SKU_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PRE_ORDER_CUST_CLASS_ID
		dataType: int64
		lineageTag: 46b5df46-694e-408b-ae95-38fb770c7ce1
		summarizeBy: count
		sourceColumn: PRE_ORDER_CUST_CLASS_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRE_ORDER_RFM_VALUE
		dataType: string
		lineageTag: 8ef892e4-039e-48ec-afcd-e5d1e282040d
		summarizeBy: none
		sourceColumn: PRE_ORDER_RFM_VALUE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CAMPAIGN
		dataType: string
		lineageTag: d64fc0b2-0b0f-480a-ba69-8cac7592b027
		summarizeBy: none
		sourceColumn: CAMPAIGN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DEVICE
		dataType: string
		lineageTag: 5fa0b28d-b5ea-4059-98d4-304e7f22f093
		summarizeBy: none
		sourceColumn: DEVICE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MEDIUM
		dataType: string
		lineageTag: a6719f30-8557-4a85-9003-79446e37e2b5
		summarizeBy: none
		sourceColumn: MEDIUM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE
		dataType: string
		lineageTag: 952e0864-41c5-4fc9-8217-81b77afe1fc7
		summarizeBy: none
		sourceColumn: SOURCE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RL_PAT_CODE
		dataType: string
		lineageTag: a852606a-39ed-45f0-84ea-76a6e1e29157
		summarizeBy: none
		sourceColumn: RL_PAT_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LONG_PAT_NAME
		dataType: string
		lineageTag: 4c91921b-16f9-498c-8804-677d2305b702
		summarizeBy: none
		sourceColumn: LONG_PAT_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PIECE_NAME
		dataType: string
		lineageTag: 61fe3b99-6f6a-44f5-8c69-8f7d0ecd1d59
		summarizeBy: none
		sourceColumn: PIECE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PIECE_CODE
		dataType: string
		lineageTag: 09fe0c0d-13b5-4da3-8f20-22d200d41068
		summarizeBy: none
		sourceColumn: PIECE_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Qty_New = IF(RELATED(SKU_Map[SKU Type]) ="Set", kbo_Query[QTY]*4,kbo_Query[QTY])
		formatString: #,0
		lineageTag: 9cdbb90b-4e2c-48b8-b138-bca54e946afa
		summarizeBy: sum

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Fiscal_Year = IF(MONTH(kbo_Query[ORDER_DT])>9, YEAR(kbo_Query[ORDER_DT])+1, YEAR(kbo_Query[ORDER_DT]))
		formatString: 0
		lineageTag: 1d4c2bb9-5d59-4851-b2f1-2729917871f0
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Customer_Type = ```
			IF(
			    OR(
			        AND(
			            DATEDIFF(
			                kbo_Query[order_dt],
			                kbo_Query[CUSTOMER_SETUP_DT],
			                DAY
			            ) >= 0,
			            DATEDIFF(
			                kbo_Query[order_dt],
			                kbo_Query[CUSTOMER_SETUP_DT],
			                DAY
			            ) <= 2
			        ),
			        AND(
			            DATEDIFF(
			                kbo_Query[order_dt],
			                kbo_Query[CUSTOMER_SETUP_DT],
			                DAY
			            ) >= -2,
			            DATEDIFF(
			                kbo_Query[order_dt],
			                kbo_Query[CUSTOMER_SETUP_DT],
			                DAY
			            ) <= 0
			        )
			    ),
			    "New",
			    "Existing"
			)
			
			```
		lineageTag: 294c4633-51ef-4788-8341-5cc66def689f
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_SETUP_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1e3dd2b2-aef9-413e-a9f0-ce2b2e520fa3
		summarizeBy: none
		sourceColumn: CUSTOMER_SETUP_DT

		variation Variation
			isDefault
			relationship: 6e516ef9-421a-44e2-aa7b-4296002638f9
			defaultHierarchy: LocalDateTable_28378ebd-fa26-4dd6-83dd-8c525319d5fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column test =
			DATEDIFF(
			        kbo_Query[order_dt],
			        kbo_Query[CUSTOMER_SETUP_DT],
			        DAY
			    )
		isHidden
		formatString: 0
		lineageTag: b242547d-7ce5-406a-a095-5fc9fbc3da2f
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition kbo_Query-115896a5-71e6-4a8d-9f05-89e50da81cc9 = m
		mode: import
		source =
				let
				    Source = Oracle.Database("rrl4", [HierarchicalNavigation=true, Query="select orders.order_id, #(lf)       orders.order_dt,#(lf)       orders.ext_entity_id,#(lf)       orders.line_items_total_amt,#(lf)       orders.pre_order_cust_class_id,#(lf)       orders.pre_order_rfm_value,#(lf)       rladmin.web_analytics_campaign.descr as Campaign,#(lf)       rladmin.web_analytics_device.descr as Device,#(lf)       rladmin.web_analytics_medium.descr as Medium,#(lf)       rladmin.web_analytics_source.descr as Source,#(lf)       rladmin.order_item.qty,#(lf)       rladmin.order_item.price,#(lf)       rladmin.order_item.sku_id,#(lf)       rladmin.order_item.setup_dt,#(lf)       rladmin.order_item.price*rladmin.order_item.qty as Revenue,#(lf)       pattern_series.rl_pat_code,#(lf)       pattern_series.descr,#(lf)       pattern_series.long_pat_name,#(lf)       piece_type.name Piece_Name,#(lf)       piece_type.rl_pce_code Piece_code,#(lf)       client.setup_dt as Customer_Setup_Dt#(lf)  from orders,#(lf)       web_analytics,#(lf)       rladmin.web_analytics_campaign,#(lf)       rladmin.web_analytics_device,#(lf)       rladmin.web_analytics_medium,#(lf)       rladmin.web_analytics_source,#(lf)       rladmin.order_item,#(lf)       rladmin.sku,#(lf)       rladmin.pattern_series,#(lf)       rladmin.piece_type,#(lf)       rladmin.client#(lf) where web_analytics_trans_id=orders.web_order_key#(lf)       and web_analytics_campaign.web_analytics_campaign_id = web_analytics.web_analytics_campaign_id#(lf)       and web_analytics_device.web_analytics_device_id = web_analytics.web_analytics_device_id#(lf)       and web_analytics_medium.web_analytics_medium_id = web_analytics.web_analytics_medium_id#(lf)       and web_analytics_source.web_analytics_source_id = web_analytics.web_analytics_source_id#(lf)       and order_item.sku_id = sku.sku_id#(lf)       and pattern_series.pat_series_id = sku.pat_series_id#(lf)       and piece_type.pce_type_id = sku.pce_type_id#(lf)       and orders.order_id = order_item.order_id#(lf)       and orders.ext_entity_id = client.client_id#(lf)       and orders.order_dt > sysdate - 1000#(lf)"]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"SETUP_DT"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"ORDER_DT", type date}, {"CUSTOMER_SETUP_DT", type date}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"ORDER_ID", "ORDER_DT", "CUSTOMER_SETUP_DT", "EXT_ENTITY_ID", "LINE_ITEMS_TOTAL_AMT", "PRE_ORDER_CUST_CLASS_ID", "PRE_ORDER_RFM_VALUE", "CAMPAIGN", "DEVICE", "MEDIUM", "SOURCE", "QTY", "PRICE", "SKU_ID", "REVENUE", "RL_PAT_CODE", "DESCR", "LONG_PAT_NAME", "PIECE_NAME", "PIECE_CODE"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"DESCR"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns1",{{"ORDER_ID", type text}, {"EXT_ENTITY_ID", type text}, {"PRE_ORDER_CUST_CLASS_ID", Int64.Type}, {"QTY", Int64.Type}, {"SKU_ID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

